CREATE DATABASE SecurityDB2025;
GO
USE SecurityDB2025;
GO
CREATE TABLE Users (
    id INT PRIMARY KEY IDENTITY(1,1),
    name VARCHAR(100) NOT NULL,
    passwordHash VARCHAR(64) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    status TINYINT NOT NULL
);